QuizAndTestSite/Controllers/QuizAndTestController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using QuizAndTestSite.Data;
using QuizAndTestSite.Models;
using System.Security.Claims;

namespace QuizAndTestSite.Controllers
{
    public class QuizAndTestController : Controller
    {

        private readonly ApplicationDbContext _db;

        public QuizAndTestController(ApplicationDbContext db)
        {
            _db = db;
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Quizes()
        {
            IEnumerable<QuizModel> objQuizModelList = _db.Quizes;

            return View(objQuizModelList);
        }

        public IActionResult Quiz(int? id)
        {

            IEnumerable<QuestionModel> objQuestionModelList = _db.Questions.Where(x => x.QuizModelId == id);

            //List objects to be used on dynamic model
            //IEnumerable<QuizModel> objQuizModelList = _db.Quizes;
            //IEnumerable<QuestionModel> objQuestionModelList = _db.Questions;
            //IEnumerable<OptionModel> objOptionModelList = _db.Options;
            //IEnumerable<ResultModel> objResultModelList = _db.Results;



            //Dynamic model which contains other models
            //dynamic mymodel = new ExpandoObject();
            //mymodel.Quizes = objQuizModelList;
            //mymodel.Questions = objQuestionModelList;
            //mymodel.Options = objOptionModelList;
            //mymodel.Results = objResultModelList;


            //ViewdData for question records
            //ViewData["questions"] = objQuestionModelList;



            return View(objQuestionModelList);
        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Quiz(ChosenOptionsModel obj)
        {
            //if (obj.ChosenOption_1 == _db.Questions.Where(x => x.Id == 1).FirstOrDefault().CorrectOption && obj.ChosenOption_2 == _db.Questions.Where(x => x.Id == 2).FirstOrDefault().CorrectOption)
            //{
            //    return Json("hll");
            //}
            //else
            //{
            //    return Json("yanlis cevap");

            //}

            ResultModel Result = new ResultModel();

            foreach (var question in _db.Questions.Where(x => x.QuizModelId == obj.Id))
            {

                if (question.CorrectOption == obj.ChosenOption_1)
                {
                    Result.CorrectAnswerCount = Result.CorrectAnswerCount + 1;
                }

                if (question.CorrectOption == obj.ChosenOption_2)
                {
                    Result.CorrectAnswerCount = Result.CorrectAnswerCount + 1;
                }

                if (question.CorrectOption == obj.ChosenOption_3)
                {
                    Result.CorrectAnswerCount = Result.CorrectAnswerCount + 1;
                }

                if (question.CorrectOption == obj.ChosenOption_4)
                {
                    Result.CorrectAnswerCount = Result.CorrectAnswerCount + 1;
                }

                if (question.CorrectOption == obj.ChosenOption_5)
                {
                    Result.CorrectAnswerCount = Result.CorrectAnswerCount + 1;
                }







            }
            int question_count = _db.Questions.Where(x => x.QuizModelId == obj.Id).Count();

            Result.Score = (100 / question_count) * Result.CorrectAnswerCount;
            Result.QuizModelId = obj.Id;
            Result.AspNetUsersId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            Result.Date = DateTime.UtcNow;

            _db.Results.Add(Result);
            _db.SaveChanges();







            return RedirectToAction("Result", Result);

        }



        public IActionResult Result(ResultModel Result)
        {
            return View(Result);
        }
    }
}

QuizAndTestSite/Views/QuizAndTest/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

QuizAndTestSite/Views/QuizAndTest/Quiz.cshtml
@{

}

@model IEnumerable<QuestionModel>

<div class="text-center container">
    <h1 class="display-4 text-capitalize fw-bold purpleText">Welcome to the quiz!</h1>

    <form method="post" asp-controller="QuizAndTest" asp-action="Quiz">



        <div class="form-group">
            @foreach (var question in Model)
            {
                <label for="question_@question" class="text-capitalize fw-bold purpleText">@question.Content</label>

                <select name="chosenoption_@question.Id" class="form-control">
                    <option value="" disabled selected>Select your option</option>
                    <option value="@question.Option_1">@question.Option_1</option>
                    <option value="@question.Option_2">@question.Option_2</option>
                    <option value="@question.Option_3">@question.Option_3</option>
                    <option value="@question.Option_4">@question.Option_4</option>
                </select>


            }
        </div>


        <br />
        @*<select name="QuizModelId" hidden class="form-control">
            <option value="QuizModelId">QuizModelId</option>
        </select>*@

        @*<input type="text" style="accent-color: mediumpurple" name="QuizModelId" hidden />*@





        @*@foreach (var item in Model)
        {
        <h1>@item.Content</h1>
        <div class="form-group">
        <label for="fromAirport">@item.Content</label>
        <select class="form-control">
        @foreach(var x in item.Optionlar){
        <option>@x.Content</option>
        }
        </select>
        </div>
        }*@







        @*<div class="form-group">
        @for (int i = 1; i < Model.Count() + 1; i++)
        {
        <label for="Question_@i+1">@Model.FirstOrDefault(u => u.Id == i).Content</label>

        <select asp-for="@Model.FirstOrDefault(u => u.Id == i).ChosenOption" class="form-control" name="Option{@i}">
        <option>@Model.FirstOrDefault(u => u.Id == i).Option1</option>
        <option>@Model.FirstOrDefault(u => u.Id == i).Option2</option>
        <option>@Model.FirstOrDefault(u => u.Id == i).Option3</option>
        <option>@Model.FirstOrDefault(u => u.Id == i).Option4</option>
        </select>

        }
        </div>*@

        <button class="btn alert-primary mt-1 purpleButton whiteText" type="submit">Send</button>
        <a asp-controller="QuizAndTest" asp-action="Quizes" class="btn btn-secondary" style="width:150px">
            Back to Menu
        </a>
    </form>


</div>

QuizAndTestSite/Views/QuizAndTest/Quizes.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model IEnumerable<QuizModel>

<div class="text-center">
    <div class="mainText">
        <h1 class="display-4 text-capitalize fw-bold purpleText">Quizes</h1>
        <h2 class="mainSubtitle purpleText">Here are our quizes</h2>
    </div>
    <img class="mainImage" style="height:300px; width:512px" src="~/images/Quizz.png" />

    <br />

    @foreach (var quiz in Model)
    {
        <a class="btn btn-primary btn-square-md" style="float: none; background-color: mediumpurple; width: 200px; height; 400px" asp-area="" asp-controller="QuizAndTest" asp-action="Quiz" asp-route-id="@quiz.Id">@quiz.QuizName</a>
    }


    <br /><br />

</div>

QuizAndTestSite/Views/QuizAndTest/Result.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model ResultModel

@*@if (Model.CorrectAnswerCount == 0 || Model.CorrectAnswerCount == 1)
{
    <h1>Your have answered @Model.CorrectAnswerCount question correctly</h1>
} else
{
    <h1>Your have answered @Model.CorrectAnswerCount questions correctly</h1>
}

<h1>Your score is: @Model.Score</h1>*@

<div class="text-center">
    <div class="mainText">
        <h1 class="display-4 text-capitalize fw-bold purpleText">Your Quiz Result</h1>
        @if (Model.CorrectAnswerCount == 0 || Model.CorrectAnswerCount == 1)
        {
            <h2>Your have answered @Model.CorrectAnswerCount question correctly</h2>
        }
        else
        {
            <h2>Your have answered @Model.CorrectAnswerCount questions correctly</h2>
        }
    </div>
    @*<img class="mainImage" style="height:300px; width:512px" src="~/images/User.jpg" />*@
    <br />
    <h1 class="display-4 text-capitalize fw-bold purpleText">Your score is: </h1>
    <h1>@Model.Score</h1>


    <br /><br />

</div>